"""Butler Hermes Tool Compiler.

Translates raw Hermes tool metadata into Butler-canonical ButlerToolSpec objects.

No Hermes tool may be registered directly into Butler's ToolRegistry.
Every Hermes tool MUST pass through this compiler first.

The compiler:
  1. Reads Hermes tool metadata (name, description, input_schema)
  2. Assigns Butler risk tier (L0 → L3) from the tier map
  3. Determines approval mode, auth mode, sandbox profile
  4. Applies Tirith security policy validation
  5. Routes to the correct Butler service owner
  6. Produces a ButlerToolSpec

Governed by: docs/00-governance/transplant-constitution.md §4
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Literal

import structlog

logger = structlog.get_logger(__name__)


# ── Risk Tiers ──────────────────────────────────────────────────────────────


class RiskTier(StrEnum):
    L0 = "L0"  # safe_auto: no approval, no logging beyond usage
    L1 = "L1"  # logged: no approval, but logged for review
    L2 = "L2"  # confirm: one-click user approval required
    L3 = "L3"  # restricted: explicit approval + elevated assurance level


# ── Butler ToolSpec ─────────────────────────────────────────────────────────


@dataclass
class ButlerToolSpec:
    """Butler-canonical tool descriptor.

    Every tool in Butler's registry is represented as this object.
    Generated by HermesToolCompiler.compile() for Hermes tools.
    Written directly for Butler-native tools.
    """

    # ── Identity ────────────────────────────────────────────────────────────
    name: str  # Butler canonical name (may differ from Hermes)
    hermes_name: str  # Original Hermes tool name (for dispatch)
    version: str = "1.0"
    description: str = ""
    category: str = "general"  # search|communication|device|file|code|memory|ai|iot|security
    butler_service_owner: str = "tools"  # Which Butler service owns this tool

    # ── Policy ──────────────────────────────────────────────────────────────
    risk_tier: RiskTier = RiskTier.L1
    approval_mode: Literal["none", "implicit", "explicit", "critical"] = "implicit"
    auth_mode: Literal["user", "service", "elevated"] = "user"
    min_assurance_level: Literal["AAL1", "AAL2", "AAL3"] = "AAL1"

    # ── Execution ────────────────────────────────────────────────────────────
    sandbox_profile: str = "none"  # none|local|docker|modal|daytona|ssh|singularity
    timeout_seconds: int = 30
    idempotency_class: Literal["safe", "idempotent", "non-idempotent"] = "safe"

    # ── Side effects ─────────────────────────────────────────────────────────
    side_effect_classes: list[str] = field(default_factory=list)
    # Possible values: file_write | network | external_api | device | message |
    #                  process_spawn | credential_access | code_execute
    has_compensation: bool = False
    compensation_handler: str | None = None

    # ── Verification ─────────────────────────────────────────────────────────
    verification_mode: Literal["none", "pre", "post", "both"] = "none"
    verification_policy: str | None = None

    # ── Visibility ───────────────────────────────────────────────────────────
    visible_tiers: list[str] = field(default_factory=lambda: ["free", "pro", "enterprise"])
    visible_channels: list[str] = field(default_factory=lambda: ["mobile", "web", "voice", "api"])
    visible_industries: list[str] = field(default_factory=lambda: ["*"])

    # ── Schemas ──────────────────────────────────────────────────────────────
    input_schema: dict = field(default_factory=dict)
    output_schema: dict = field(default_factory=dict)

    # ── Security flags ───────────────────────────────────────────────────────
    blocked: bool = False  # True = FORBIDDEN, never execute
    block_reason: str = ""
    enabled: bool = True  # Whether tool is enabled for execution

    @property
    def canonical_name(self) -> str:
        """Return the canonical name of the tool."""
        return self.name


# ── Tier assignment table ────────────────────────────────────────────────────
# Maps Hermes tool name → (risk_tier, butler_service_owner, sandbox, side_effects)

_HERMES_TOOL_TIER_MAP: dict[str, dict] = {
    # ── L0: safe_auto — no approval ─────────────────────────────────────────
    "web_search": {
        "tier": RiskTier.L0,
        "owner": "search",
        "sandbox": "none",
        "side_effects": ["network"],
        "description": "Search the web for current information, news, weather, facts, or any real-time data. Use this for any question requiring up-to-date or external knowledge.",
    },
    "memory_recall": {
        "tier": RiskTier.L0,
        "owner": "memory",
        "sandbox": "none",
        "side_effects": [],
        "description": "Recall information from the user's long-term memory store, including past conversations, preferences, and stored facts.",
        "blocked": True,
        "block_reason": "No direct implementation - use memory service instead",
    },
    "session_search": {
        "tier": RiskTier.L0,
        "owner": "memory",
        "sandbox": "none",
        "side_effects": [],
        "description": "Search the current session's conversation history for relevant context or previously mentioned information.",
        "blocked": True,
        "block_reason": "No direct implementation - use memory service instead",
    },
    "list_files": {
        "tier": RiskTier.L0,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "description": "List files and directories in the user's workspace.",
        "blocked": True,
        "block_reason": "No direct implementation - use file service instead",
    },
    "read_file": {
        "tier": RiskTier.L0,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": [],
        "description": "Read the contents of a file from the user's workspace.",
        "blocked": True,
        "block_reason": "No direct implementation - use file service instead",
    },
    "clarify": {
        "tier": RiskTier.L0,
        "owner": "orchestrator",
        "sandbox": "none",
        "side_effects": [],
        "description": "Ask the user a clarifying question when their request is ambiguous or requires more information to proceed.",
        "blocked": True,
        "block_reason": "No direct implementation - handled by orchestrator",
    },
    "get_time": {
        "tier": RiskTier.L0,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "description": "Get the current date and time.",
        "input_schema": {
            "type": "object",
            "properties": {
                "timezone": {
                    "type": "string",
                    "description": "IANA timezone (e.g., 'UTC', 'Asia/Kolkata')",
                }
            },
        },
        "output_schema": {
            "type": "object",
            "properties": {
                "timezone": {"type": "string"},
                "iso": {"type": "string"},
                "date": {"type": "string"},
                "time": {"type": "string"},
                "weekday": {"type": "string"},
            },
        },
    },
    "fuzzy_match": {
        "tier": RiskTier.L0,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "description": "Perform fuzzy string matching to find the closest match from a list of candidates.",
        "blocked": True,
        "block_reason": "No direct implementation",
    },
    "url_safety_check": {
        "tier": RiskTier.L0,
        "owner": "security",
        "sandbox": "none",
        "side_effects": ["network"],
        "description": "Check whether a URL is safe to visit by scanning for malware, phishing, or other threats.",
        "blocked": True,
        "block_reason": "No direct implementation - use butler_url_safety module instead",
    },
    "osv_check": {
        "tier": RiskTier.L0,
        "owner": "security",
        "sandbox": "none",
        "side_effects": ["network"],
        "description": "Check a software package for known vulnerabilities using the OSV (Open Source Vulnerabilities) database.",
        "blocked": True,
        "block_reason": "No direct implementation",
    },
    "system_stats": {
        "tier": RiskTier.L0,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "description": "Get system resource statistics including CPU, memory, and disk usage.",
        "blocked": True,
        "block_reason": "No direct implementation",
    },
    # ── L1: logged — no approval, audit trail ─────────────────────────────
    "transcribe_audio": {
        "tier": RiskTier.L1,
        "owner": "audio",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use audio service instead",
    },
    "synthesize_speech": {
        "tier": RiskTier.L1,
        "owner": "audio",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use audio service instead",
    },
    "vision_analyze": {
        "tier": RiskTier.L1,
        "owner": "vision",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use vision service instead",
    },
    "image_generate": {
        "tier": RiskTier.L1,
        "owner": "ml",
        "sandbox": "none",
        "side_effects": ["external_api"],
        "blocked": True,
        "block_reason": "No direct implementation - use ML runtime instead",
    },
    "todo_list": {
        "tier": RiskTier.L1,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use task management service instead",
    },
    "get_credential": {
        "tier": RiskTier.L1,
        "owner": "auth",
        "sandbox": "none",
        "side_effects": ["credential_access"],
        "blocked": True,
        "block_reason": "No direct implementation - use auth service instead",
    },
    "list_skills": {
        "tier": RiskTier.L1,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use skills hub service instead",
    },
    "get_skill_plan": {
        "tier": RiskTier.L1,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": [],
        "blocked": True,
        "block_reason": "No direct implementation - use skills hub service instead",
    },
    # ── L2: confirm — one-click approval ──────────────────────────────────
    "write_file": {
        "tier": RiskTier.L2,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": ["file_write"],
    },
    "patch_file": {
        "tier": RiskTier.L2,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": ["file_write"],
    },
    "send_message": {
        "tier": RiskTier.L2,
        "owner": "communication",
        "sandbox": "none",
        "side_effects": ["message"],
    },
    "create_cron_job": {
        "tier": RiskTier.L2,
        "owner": "automation",
        "sandbox": "none",
        "side_effects": [],
    },
    "delete_cron_job": {
        "tier": RiskTier.L2,
        "owner": "automation",
        "sandbox": "none",
        "side_effects": [],
    },
    "delegate": {
        "tier": RiskTier.L2,
        "owner": "orchestrator",
        "sandbox": "none",
        "side_effects": [],
    },
    "mixture_of_agents": {
        "tier": RiskTier.L2,
        "owner": "orchestrator",
        "sandbox": "none",
        "side_effects": [],
    },
    "skill_install": {"tier": RiskTier.L2, "owner": "tools", "sandbox": "none", "side_effects": []},
    "mcp_connect": {
        "tier": RiskTier.L2,
        "owner": "tools",
        "sandbox": "none",
        "side_effects": ["external_api"],
    },
    # ── L3: restricted — elevated assurance + explicit approval ───────────
    "run_terminal": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": ["process_spawn", "file_write", "network"],
    },
    "code_execution": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": ["code_execute", "file_write"],
    },
    "browser_automation": {
        "tier": RiskTier.L3,
        "owner": "search",
        "sandbox": "docker",
        "side_effects": ["network"],
    },
    "firecrawl": {
        "tier": RiskTier.L3,
        "owner": "search",
        "sandbox": "none",
        "side_effects": ["network", "external_api"],
    },
    "homeassistant_control": {
        "tier": RiskTier.L3,
        "owner": "device",
        "sandbox": "none",
        "side_effects": ["device", "external_api"],
    },
    "rl_training": {
        "tier": RiskTier.L3,
        "owner": "ml",
        "sandbox": "docker",
        "side_effects": ["code_execute", "file_write"],
    },
    "env_docker": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "docker",
        "side_effects": ["code_execute"],
    },
    "env_modal": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "modal",
        "side_effects": ["code_execute", "external_api"],
    },
    "env_ssh": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "ssh",
        "side_effects": ["network", "process_spawn"],
    },
    "env_daytona": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "daytona",
        "side_effects": ["code_execute", "external_api"],
    },
    "env_singularity": {
        "tier": RiskTier.L3,
        "owner": "tools",
        "sandbox": "singularity",
        "side_effects": ["code_execute"],
    },
}

# Tools that are FORBIDDEN in Butler regardless of account tier
_FORBIDDEN_TOOLS: dict[str, str] = {
    "butler_db_direct": "Attempts to write Butler PostgreSQL directly",
    "bypass_auth": "Bypasses Butler authentication",
    "raw_credential_write": "Writes credentials without Butler credential pool",
}

# Approval mode per risk tier
_APPROVAL_MODE = {
    RiskTier.L0: "none",
    RiskTier.L1: "implicit",
    RiskTier.L2: "explicit",
    RiskTier.L3: "critical",
}

# Min assurance level per risk tier
_MIN_ASSURANCE = {
    RiskTier.L0: "AAL1",
    RiskTier.L1: "AAL1",
    RiskTier.L2: "AAL2",
    RiskTier.L3: "AAL3",
}

# Tier visibility defaults (which product tiers can see each risk tier)
_TIER_VISIBILITY = {
    RiskTier.L0: ["free", "pro", "enterprise"],
    RiskTier.L1: ["free", "pro", "enterprise"],
    RiskTier.L2: ["pro", "enterprise"],
    RiskTier.L3: ["enterprise"],
}


class HermesToolCompiler:
    """Compiles Hermes tool definitions into Butler ButlerToolSpec objects.

    Usage:
        compiler = HermesToolCompiler()
        spec = compiler.compile("web_search", hermes_metadata)
        butler_tool_registry.register(spec)

    Or bulk-compile all Hermes tools:
        specs = compiler.compile_all()
        for spec in specs:
            butler_tool_registry.register(spec)
    """

    def compile(self, hermes_name: str, hermes_meta: dict) -> ButlerToolSpec:
        """Compile a single Hermes tool into a ButlerToolSpec.

        Args:
            hermes_name: The tool's name in Hermes (e.g. "web_search")
            hermes_meta: Raw metadata dict from Hermes tools/registry.py

        Returns:
            ButlerToolSpec ready for registration in Butler's ToolRegistry
        """
        # Check forbidden list
        if hermes_name in _FORBIDDEN_TOOLS:
            return ButlerToolSpec(
                name=hermes_name,
                hermes_name=hermes_name,
                description=_FORBIDDEN_TOOLS[hermes_name],
                blocked=True,
                block_reason=_FORBIDDEN_TOOLS[hermes_name],
                risk_tier=RiskTier.L3,
                input_schema={},
                output_schema={},
            )

        # Get tier config or default to L2
        tier_config = _HERMES_TOOL_TIER_MAP.get(
            hermes_name,
            {
                "tier": RiskTier.L2,
                "owner": "tools",
                "sandbox": "none",
                "side_effects": [],
            },
        )

        # Check if tool is blocked in tier config
        if tier_config.get("blocked", False):
            return ButlerToolSpec(
                name=hermes_name,
                hermes_name=hermes_name,
                description=tier_config.get("description", "Blocked tool"),
                blocked=True,
                block_reason=tier_config.get("block_reason", "Blocked in tier configuration"),
                risk_tier=tier_config.get("tier", RiskTier.L2),
                input_schema={},
                output_schema={},
            )

        tier = tier_config["tier"]
        owner = tier_config["owner"]
        sandbox = tier_config["sandbox"]
        side_effects = tier_config["side_effects"]

        if hermes_name not in _HERMES_TOOL_TIER_MAP:
            logger.warning(
                "hermes_tool_unknown_tier",
                hermes_name=hermes_name,
                assigned_tier=tier.value,
                message="Tool not in tier map — defaulting to L2/confirm. "
                "Add it to _HERMES_TOOL_TIER_MAP with explicit tier.",
            )

        # Determine verification mode
        verification_mode = "none"
        if "file_write" in side_effects or "code_execute" in side_effects:
            verification_mode = "post"
        if "device" in side_effects:
            verification_mode = "both"

        spec = ButlerToolSpec(
            name=hermes_name,
            hermes_name=hermes_name,
            version=hermes_meta.get("version", "1.0"),
            description=hermes_meta.get("description", ""),
            category=hermes_meta.get("category", "general"),
            butler_service_owner=owner,
            risk_tier=tier,
            approval_mode=_APPROVAL_MODE[tier],
            auth_mode="elevated" if tier == RiskTier.L3 else "user",
            min_assurance_level=_MIN_ASSURANCE[tier],
            sandbox_profile=sandbox,
            timeout_seconds=hermes_meta.get("timeout_seconds", 30),
            idempotency_class=hermes_meta.get("idempotency_class", "safe"),
            side_effect_classes=side_effects,
            has_compensation="file_write" in side_effects or "message" in side_effects,
            verification_mode=verification_mode,
            visible_tiers=_TIER_VISIBILITY[tier],
            visible_channels=hermes_meta.get("visible_channels", ["mobile", "web", "voice", "api"]),
            visible_industries=hermes_meta.get("visible_industries", ["*"]),
            input_schema=hermes_meta.get("input_schema") or tier_config.get("input_schema", {}),
            output_schema=hermes_meta.get("output_schema") or tier_config.get("output_schema", {}),
        )

        logger.debug(
            "hermes_tool_compiled",
            hermes_name=hermes_name,
            risk_tier=tier.value,
            owner=owner,
            approval_mode=spec.approval_mode,
        )

        return spec

    def compile_all(self) -> list[ButlerToolSpec]:
        """Compile all known Hermes tools using the tier map.

        In production, this is called once at startup to populate
        Butler's ToolRegistry from Hermes tool definitions.
        """
        try:
            from integrations.hermes.tools.registry import get_all_tool_definitions

            hermes_tools = get_all_tool_definitions()
        except ImportError as exc:
            logger.warning(
                "hermes_tool_registry_unavailable",
                message="Using tier map only — Hermes tool registry not importable",
                error=str(exc),
                exc_info=True,
            )
            hermes_tools = {}

        specs: list[ButlerToolSpec] = []

        # Compile all tools in the tier map
        for hermes_name, _tier_config in _HERMES_TOOL_TIER_MAP.items():
            meta = hermes_tools.get(hermes_name, {})
            # Fall back to tier map description when Hermes registry is unavailable
            if not meta.get("description") and _tier_config.get("description"):
                meta = {**meta, "description": _tier_config["description"]}
            spec = self.compile(hermes_name, meta)
            specs.append(spec)

        # Compile any additional Hermes tools not in the tier map
        for name, meta in hermes_tools.items():
            if name not in _HERMES_TOOL_TIER_MAP and name not in _FORBIDDEN_TOOLS:
                spec = self.compile(name, meta)
                specs.append(spec)

        logger.info(
            "hermes_tools_compiled",
            total=len(specs),
            blocked=sum(1 for s in specs if s.blocked),
            l0=sum(1 for s in specs if not s.blocked and s.risk_tier == RiskTier.L0),
            l1=sum(1 for s in specs if not s.blocked and s.risk_tier == RiskTier.L1),
            l2=sum(1 for s in specs if not s.blocked and s.risk_tier == RiskTier.L2),
            l3=sum(1 for s in specs if not s.blocked and s.risk_tier == RiskTier.L3),
        )

        return specs
