"""ButlerStreamDispatcher — Phase 6b.

Bridges Butler canonical events from the Orchestrator's stream into
the Realtime delivery layer (Redis Streams + WebSocket fan-out).

Responsibilities:
  1. Receive ButlerEvents from OrchestratorService.intake_streaming()
  2. Map them to RealtimeEvents using the canonical event vocabulary
  3. Push durable events to Redis Streams (xadd) for replay
  4. Fan-out to connected WebSocket clients via ConnectionManager
  5. Expose an SSE replay endpoint: pull from Redis Stream with cursor

Sovereignty rules:
  - StreamDispatcher never calls Hermes directly.
  - It only speaks Butler event vocabulary (ButlerEvent subtypes).
  - Hermes-internal event names (like "reasoning_tag") are scrubbed by
    EventNormalizer before they ever reach this layer.
  - durable=False events (response.chunk ephemeral) are never persisted.

Redis Stream design:
  - Stream key:  butler:events:{account_id}
  - MAXLEN:      1000 per account (approximate trimming)
  - Entry IDs:   auto-generated by Redis (millisecond precision)
  - Cursor:      last seen entry ID from client resume message
  - Replay TTL:  48 hours via EXPIRE on the stream key
"""

from __future__ import annotations

import json
import time
from datetime import datetime, UTC
from typing import AsyncGenerator, Literal

import structlog
from redis.asyncio import Redis

from domain.events.schemas import (
    ButlerEvent,
    StreamTokenEvent,
    StreamFinalEvent,
    StreamToolCallEvent,
    StreamApprovalRequiredEvent,
    StreamErrorEvent,
)
from services.realtime.events import RealtimeEvent, Events
from services.realtime.manager import ConnectionManager

logger = structlog.get_logger(__name__)

_STREAM_PREFIX = "butler:events:"
_STREAM_MAXLEN = 1000
_STREAM_TTL_S = 172_800   # 48h
_REPLAY_DEFAULT_COUNT = 50


class ButlerStreamDispatcher:
    """Routes ButlerEvents to Redis Streams and WebSocket fan-out.

    Usage:
        dispatcher = ButlerStreamDispatcher(redis=redis, manager=conn_manager)

        async for event in orchestrator.intake_streaming(envelope):
            await dispatcher.dispatch(event, account_id="acct_1")
    """

    def __init__(
        self,
        redis: Redis,
        manager: ConnectionManager | None = None,
    ) -> None:
        self._redis = redis
        self._manager = manager

    async def dispatch(self, event: ButlerEvent, account_id: str) -> None:
        """Route a single ButlerEvent to the appropriate realtime channel."""
        rt_event = self._map_to_realtime(event)
        if rt_event is None:
            return

        # 1. WebSocket fan-out (best-effort — no error on disconnect)
        if self._manager:
            try:
                await self._manager.send_event(account_id, rt_event)
            except Exception as exc:
                logger.debug("ws_send_skipped", account_id=account_id, error=str(exc))

        # 2. Durable events → Redis Stream
        if rt_event.durable:
            await self._persist_to_stream(account_id, rt_event)

    async def dispatch_batch(
        self, events: list[ButlerEvent], account_id: str
    ) -> None:
        for ev in events:
            await self.dispatch(ev, account_id)

    # ── SSE Replay ────────────────────────────────────────────────────────────

    async def replay(
        self,
        account_id: str,
        cursor: str = "0",
        count: int = _REPLAY_DEFAULT_COUNT,
    ) -> list[dict]:
        """Fetch events from Redis Stream starting from cursor.

        Returns list of dicts ready for SSE serialization.
        cursor = "0"  → replay from beginning
        cursor = "$"  → only new events (live tail)
        cursor = "<redis_stream_id>"  → resume from last seen
        """
        stream_key = _STREAM_PREFIX + account_id
        try:
            entries = await self._redis.xrange(
                stream_key,
                min=cursor,
                count=count,
            )
        except Exception as exc:
            logger.warning("stream_replay_error", account_id=account_id, error=str(exc))
            return []

        results = []
        for entry_id, fields in entries:
            # entry_id and field values may be bytes
            eid = entry_id.decode() if isinstance(entry_id, bytes) else entry_id
            decoded = {}
            for k, v in fields.items():
                key = k.decode() if isinstance(k, bytes) else k
                val = v.decode() if isinstance(v, bytes) else v
                decoded[key] = val
            results.append({"id": eid, **decoded})

        return results

    async def sse_replay_stream(
        self,
        account_id: str,
        cursor: str = "0",
        count: int = _REPLAY_DEFAULT_COUNT,
    ) -> AsyncGenerator[str, None]:
        """Async generator of SSE-formatted replayed events.

        Usage in FastAPI route:
            return StreamingResponse(
                dispatcher.sse_replay_stream(account_id, cursor),
                media_type="text/event-stream",
            )
        """
        entries = await self.replay(account_id, cursor, count)
        for entry in entries:
            eid = entry.get("id", "")
            event_type = entry.get("type", "butler.event")
            payload = entry.get("payload", "{}")
            ts = entry.get("timestamp", "")
            yield (
                f"id: {eid}\n"
                f"event: {event_type}\n"
                f"data: {payload}\n"
                f"X-Ts: {ts}\n\n"
            )
        # Signal end of replay
        yield "event: replay.complete\ndata: {}\n\n"

    # ── Event mapping ─────────────────────────────────────────────────────────

    def _map_to_realtime(self, event: ButlerEvent) -> RealtimeEvent | None:
        """Map a ButlerEvent to a RealtimeEvent.

        Returns None for event types that should not be forwarded
        (e.g. internal debug events).
        """
        match event.event_type:
            case "stream.token":
                content = event.payload.get("content", "")
                final = event.payload.get("final", False)
                return Events.response_chunk(content, final=final)

            case "workflow.complete":
                return RealtimeEvent(
                    event_type="workflow.complete",
                    payload={
                        "workflow_id": event.payload.get("workflow_id", ""),
                        "content": event.payload.get("content", ""),
                        "duration_ms": event.payload.get("duration_ms", 0),
                    },
                    durable=True,
                )

            case "tool.call":
                return RealtimeEvent(
                    event_type="tool.call",
                    payload={
                        "tool_name": event.payload.get("tool_name", ""),
                        "status": event.payload.get("status", "running"),
                        "result": event.payload.get("result"),
                    },
                    durable=True,
                )

            case "approval.request":
                return RealtimeEvent(
                    event_type="approval.request",
                    payload={
                        "approval_id": event.payload.get("approval_id", ""),
                        "description": event.payload.get("description", ""),
                        "tool_name": event.payload.get("tool_name", ""),
                    },
                    durable=True,
                )

            case "error":
                return RealtimeEvent(
                    event_type="error",
                    payload={
                        "type": event.payload.get("type", "internal-error"),
                        "title": event.payload.get("title", "Error"),
                        "status": event.payload.get("status", 500),
                        "detail": event.payload.get("detail", ""),
                    },
                    durable=True,
                )

            case _:
                # Unknown event types are not forwarded
                logger.debug("stream_dispatcher_skipped_event", event_type=event.event_type)
                return None

    # ── Private ───────────────────────────────────────────────────────────────

    async def _persist_to_stream(
        self, account_id: str, event: RealtimeEvent
    ) -> None:
        """Write a durable event to the account's Redis Stream."""
        stream_key = _STREAM_PREFIX + account_id
        try:
            # Redis XADD requires all field values to be strings
            payload_str = (
                event.payload.get("content", json.dumps(event.payload))
                if isinstance(event.payload.get("content"), str)
                else json.dumps(event.payload)
            )
            entry = {
                "type": event.event_type,
                "payload": payload_str,
                "timestamp": event.timestamp.isoformat(),
                "event_id": event.event_id,
            }
            await self._redis.xadd(stream_key, entry, maxlen=_STREAM_MAXLEN)
            # Refresh TTL on every write — sliding 48h window
            await self._redis.expire(stream_key, _STREAM_TTL_S)
        except Exception as exc:
            # Never let stream persistence failure break the hot path
            logger.warning(
                "stream_persist_failed",
                account_id=account_id,
                event_type=event.event_type,
                error=str(exc),
            )
