"""add orchestration tables

Revision ID: 8b5d0ea168c8
Revises: 001
Create Date: 2026-04-20 20:10:02.602550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '8b5d0ea168c8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comm_consent_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comm_consent_states_recipient'), 'comm_consent_states', ['recipient'], unique=False)
    op.create_table('comm_delivery_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sender_profile_id', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('terminal', sa.Boolean(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_status_raw', sa.String(length=255), nullable=True),
    sa.Column('provider_event_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_provider_acceptance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comm_delivery_records_provider_message_id'), 'comm_delivery_records', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_comm_delivery_records_recipient'), 'comm_delivery_records', ['recipient'], unique=False)
    op.create_table('comm_sender_profiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resource_pressure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret', sa.String(length=120), nullable=True),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.Text(), nullable=False),
    sa.Column('response_types', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_table('speaker_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_speaker_profiles_account_id'), 'speaker_profiles', ['account_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_account_id'), 'tool_executions', ['account_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_idempotency_key'), 'tool_executions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_tool_executions_task_id'), 'tool_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_name'), 'tool_executions', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_executions_workflow_id'), 'tool_executions', ['workflow_id'], unique=False)
    op.create_table('episode_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speaker_profile_id', sa.Uuid(), nullable=False),
    sa.Column('num_segments', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('default_briefing', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['speaker_profile_id'], ['speaker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_episode_profiles_account_id'), 'episode_profiles', ['account_id'], unique=False)
    op.create_table('oauth_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=True),
    sa.Column('code_challenge_method', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_oauth_codes_client_id'), 'oauth_codes', ['client_id'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('backup_eligible', sa.Boolean(), nullable=False),
    sa.Column('backup_state', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_embeddings_source_id'), 'source_embeddings', ['source_id'], unique=False)
    op.create_table('source_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('insight_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_insights_source_id'), 'source_insights', ['source_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_workflow_id'), 'workflow_events', ['workflow_id'], unique=False)
    op.create_table('workflow_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('signal_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_signals_workflow_id'), 'workflow_signals', ['workflow_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_task_id'), 'approval_requests', ['task_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_account_id', sa.UUID(), nullable=False),
    sa.Column('trust_state', sa.String(length=32), nullable=False),
    sa.Column('online_state', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_transitions_task_id'), 'task_transitions', ['task_id'], unique=False)
    op.drop_table('butler_cron_jobs')
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_turns_session'), table_name='conversation_turns')
    op.create_index(op.f('ix_conversation_turns_account_id'), 'conversation_turns', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.drop_constraint(op.f('conversation_turns_account_id_fkey'), 'conversation_turns', type_='foreignkey')
    op.alter_column('explicit_dislikes', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_index(op.f('ix_explicit_dislikes_account_id'), 'explicit_dislikes', ['account_id'], unique=False)
    op.drop_constraint(op.f('explicit_dislikes_account_id_fkey'), 'explicit_dislikes', type_='foreignkey')
    op.alter_column('explicit_preferences', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_index(op.f('ix_explicit_preferences_account_id'), 'explicit_preferences', ['account_id'], unique=False)
    op.drop_constraint(op.f('explicit_preferences_account_id_fkey'), 'explicit_preferences', type_='foreignkey')
    op.drop_index(op.f('uq_identities_type_identifier'), table_name='identities')
    op.create_unique_constraint('uq_identities_type_identifier', 'identities', ['identity_type', 'identifier'])
    op.alter_column('knowledge_chunks', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('knowledge_chunks', 'index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_chunks', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               postgresql_using="embedding::text::vector(1536)",
               existing_nullable=True)
    op.create_index(op.f('ix_knowledge_chunks_account_id'), 'knowledge_chunks', ['account_id'], unique=False)
    op.drop_constraint(op.f('knowledge_chunks_account_id_fkey'), 'knowledge_chunks', type_='foreignkey')
    op.alter_column('knowledge_edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_knowledge_edges_account_id'), 'knowledge_edges', ['account_id'], unique=False)
    op.drop_constraint(op.f('knowledge_edges_account_id_fkey'), 'knowledge_edges', type_='foreignkey')
    op.alter_column('knowledge_entities', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_entities', 'name_embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               postgresql_using="name_embedding::text::vector(1536)",
               existing_nullable=True)
    op.alter_column('knowledge_entities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('knowledge_entities', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('ACTIVE', 'DEPRECATED', 'CONFLICTED', name='memorystatus', native_enum=False),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_knowledge_entities_account_id'), 'knowledge_entities', ['account_id'], unique=False)
    op.drop_constraint(op.f('knowledge_entities_account_id_fkey'), 'knowledge_entities', type_='foreignkey')
    op.alter_column('memory_entries', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               postgresql_using="embedding::text::vector(1536)",
               existing_nullable=True)
    op.alter_column('memory_entries', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('memory_entries', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('memory_entries', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'conversation'::character varying"))
    op.alter_column('memory_entries', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('memory_entries', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('ACTIVE', 'DEPRECATED', 'CONFLICTED', name='memorystatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('memory_entries', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_memory_entries_account_id'), 'memory_entries', ['account_id'], unique=False)
    op.drop_constraint(op.f('memory_entries_account_id_fkey'), 'memory_entries', type_='foreignkey')
    op.alter_column('memory_episodes', 'goal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('memory_episodes', 'outcome',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('memory_episodes', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('memory_episodes', 'lessons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('ix_memory_episodes_account_id'), 'memory_episodes', ['account_id'], unique=False)
    op.drop_constraint(op.f('memory_episodes_account_id_fkey'), 'memory_episodes', type_='foreignkey')
    op.alter_column('memory_routines', 'occurrences',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('memory_routines', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_memory_routines_account_id'), 'memory_routines', ['account_id'], unique=False)
    op.drop_constraint(op.f('memory_routines_account_id_fkey'), 'memory_routines', type_='foreignkey')
    op.alter_column('notebooks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notebooks', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notebooks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_notebooks_account_id'), 'notebooks', ['account_id'], unique=False)
    op.drop_constraint(op.f('notebooks_account_id_fkey'), 'notebooks', type_='foreignkey')
    op.add_column('notes', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('notes', 'note_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'human'::character varying"))
    op.create_index(op.f('ix_notes_account_id'), 'notes', ['account_id'], unique=False)
    op.drop_constraint(op.f('notes_account_id_fkey'), 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_principals_email'), table_name='principals')
    op.add_column('sources', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sources', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_sources_account_id'), 'sources', ['account_id'], unique=False)
    op.drop_constraint(op.f('sources_account_id_fkey'), 'sources', type_='foreignkey')
    op.add_column('tasks', sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('retries', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('compensation_task_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('tasks', 'input_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'output_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'tool_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_id'), 'tasks', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('tasks_workflow_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_parent_task_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.add_column('tool_definitions', sa.Column('requires_approval', sa.Boolean(), nullable=False))
    op.add_column('tool_definitions', sa.Column('idempotent', sa.Boolean(), nullable=False))
    op.add_column('tool_definitions', sa.Column('timeout_seconds', sa.Integer(), nullable=False))
    op.add_column('tool_definitions', sa.Column('compensation_handler', sa.String(length=64), nullable=True))
    op.add_column('tool_definitions', sa.Column('version', sa.String(length=16), nullable=False))
    op.alter_column('tool_definitions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tool_definitions', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('tool_definitions_name_key'), 'tool_definitions', type_='unique')
    op.create_index(op.f('ix_tool_definitions_name'), 'tool_definitions', ['name'], unique=True)
    op.drop_column('tool_definitions', 'created_at')
    op.alter_column('user_constraints', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_user_constraints_account_id'), 'user_constraints', ['account_id'], unique=False)
    op.drop_constraint(op.f('user_constraints_account_id_fkey'), 'user_constraints', type_='foreignkey')
    op.add_column('workflows', sa.Column('intent', sa.String(length=64), nullable=True))
    op.add_column('workflows', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflows', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workflows', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('workflows', 'plan_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflows', 'state_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflows', 'idempotency_key',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_workflows_account_id'), 'workflows', ['account_id'], unique=False)
    op.create_index(op.f('ix_workflows_idempotency_key'), 'workflows', ['idempotency_key'], unique=False)
    op.drop_constraint(op.f('workflows_account_id_fkey'), 'workflows', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('workflows_account_id_fkey'), 'workflows', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflows_idempotency_key'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_account_id'), table_name='workflows')
    op.alter_column('workflows', 'idempotency_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('workflows', 'state_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflows', 'plan_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('workflows', 'version')
    op.drop_column('workflows', 'tags')
    op.drop_column('workflows', 'context_snapshot')
    op.drop_column('workflows', 'intent')
    op.create_foreign_key(op.f('user_constraints_account_id_fkey'), 'user_constraints', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_constraints_account_id'), table_name='user_constraints')
    op.alter_column('user_constraints', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('tool_definitions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tool_definitions_name'), table_name='tool_definitions')
    op.create_unique_constraint(op.f('tool_definitions_name_key'), 'tool_definitions', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tool_definitions', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tool_definitions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tool_definitions', 'version')
    op.drop_column('tool_definitions', 'compensation_handler')
    op.drop_column('tool_definitions', 'timeout_seconds')
    op.drop_column('tool_definitions', 'idempotent')
    op.drop_column('tool_definitions', 'requires_approval')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_parent_task_id_fkey'), 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_workflow_id_fkey'), 'tasks', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_workflow_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.alter_column('tasks', 'tool_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('tasks', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'idempotency_key')
    op.drop_column('tasks', 'version')
    op.drop_column('tasks', 'compensation_task_id')
    op.drop_column('tasks', 'max_retries')
    op.drop_column('tasks', 'retries')
    op.drop_column('tasks', 'error_data')
    op.create_foreign_key(op.f('sources_account_id_fkey'), 'sources', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sources_account_id'), table_name='sources')
    op.drop_column('sources', 'updated_at')
    op.drop_column('sources', 'metadata')
    op.drop_column('sources', 'topics')
    op.create_index(op.f('ix_principals_email'), 'principals', ['email'], unique=True)
    op.create_foreign_key(op.f('notes_account_id_fkey'), 'notes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_account_id'), table_name='notes')
    op.alter_column('notes', 'note_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'human'::character varying"))
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'metadata')
    op.create_foreign_key(op.f('notebooks_account_id_fkey'), 'notebooks', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notebooks_account_id'), table_name='notebooks')
    op.alter_column('notebooks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('notebooks', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notebooks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(op.f('memory_routines_account_id_fkey'), 'memory_routines', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_memory_routines_account_id'), table_name='memory_routines')
    op.alter_column('memory_routines', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('memory_routines', 'occurrences',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_foreign_key(op.f('memory_episodes_account_id_fkey'), 'memory_episodes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_memory_episodes_account_id'), table_name='memory_episodes')
    op.alter_column('memory_episodes', 'lessons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('memory_episodes', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('memory_episodes', 'outcome',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('memory_episodes', 'goal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('memory_entries_account_id_fkey'), 'memory_entries', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_memory_entries_account_id'), table_name='memory_entries')
    op.alter_column('memory_entries', 'access_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('memory_entries', 'status',
               existing_type=sa.Enum('ACTIVE', 'DEPRECATED', 'CONFLICTED', name='memorystatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('memory_entries', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('memory_entries', 'source',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'conversation'::character varying"))
    op.alter_column('memory_entries', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('memory_entries', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('memory_entries', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(op.f('knowledge_entities_account_id_fkey'), 'knowledge_entities', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_knowledge_entities_account_id'), table_name='knowledge_entities')
    op.alter_column('knowledge_entities', 'status',
               existing_type=sa.Enum('ACTIVE', 'DEPRECATED', 'CONFLICTED', name='memorystatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('knowledge_entities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('knowledge_entities', 'name_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_entities', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('knowledge_edges_account_id_fkey'), 'knowledge_edges', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_knowledge_edges_account_id'), table_name='knowledge_edges')
    op.alter_column('knowledge_edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key(op.f('knowledge_chunks_account_id_fkey'), 'knowledge_chunks', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_knowledge_chunks_account_id'), table_name='knowledge_chunks')
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('knowledge_chunks', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('knowledge_chunks', 'index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('knowledge_chunks', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_identities_type_identifier', 'identities', type_='unique')
    op.create_index(op.f('uq_identities_type_identifier'), 'identities', ['identity_type', 'identifier'], unique=True)
    op.create_foreign_key(op.f('explicit_preferences_account_id_fkey'), 'explicit_preferences', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_explicit_preferences_account_id'), table_name='explicit_preferences')
    op.alter_column('explicit_preferences', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_foreign_key(op.f('explicit_dislikes_account_id_fkey'), 'explicit_dislikes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_explicit_dislikes_account_id'), table_name='explicit_dislikes')
    op.alter_column('explicit_dislikes', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_foreign_key(op.f('conversation_turns_account_id_fkey'), 'conversation_turns', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_account_id'), table_name='conversation_turns')
    op.create_index(op.f('ix_conversation_turns_session'), 'conversation_turns', ['session_id'], unique=False)
    op.alter_column('conversation_turns', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('butler_cron_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('cron_expression', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('butler_cron_jobs_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('butler_cron_jobs_pkey'))
    )
    op.drop_index(op.f('ix_task_transitions_task_id'), table_name='task_transitions')
    op.drop_table('task_transitions')
    op.drop_table('devices')
    op.drop_index(op.f('ix_approval_requests_task_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_workflow_signals_workflow_id'), table_name='workflow_signals')
    op.drop_table('workflow_signals')
    op.drop_index(op.f('ix_workflow_events_workflow_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_source_insights_source_id'), table_name='source_insights')
    op.drop_table('source_insights')
    op.drop_index(op.f('ix_source_embeddings_source_id'), table_name='source_embeddings')
    op.drop_table('source_embeddings')
    op.drop_table('recovery_codes')
    op.drop_table('password_reset_tokens')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_oauth_codes_client_id'), table_name='oauth_codes')
    op.drop_table('oauth_codes')
    op.drop_index(op.f('ix_episode_profiles_account_id'), table_name='episode_profiles')
    op.drop_table('episode_profiles')
    op.drop_index(op.f('ix_tool_executions_workflow_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_tool_name'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_task_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_idempotency_key'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_account_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_speaker_profiles_account_id'), table_name='speaker_profiles')
    op.drop_table('speaker_profiles')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_table('nodes')
    op.drop_table('comm_sender_profiles')
    op.drop_index(op.f('ix_comm_delivery_records_recipient'), table_name='comm_delivery_records')
    op.drop_index(op.f('ix_comm_delivery_records_provider_message_id'), table_name='comm_delivery_records')
    op.drop_table('comm_delivery_records')
    op.drop_index(op.f('ix_comm_consent_states_recipient'), table_name='comm_consent_states')
    op.drop_table('comm_consent_states')
    # ### end Alembic commands ###
