"""Common API schemas shared across services."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ErrorResponse(BaseModel):
    """RFC 9457 Problem Details response schema — for OpenAPI docs only.

    Actual responses are generated by core/errors.py with
    application/problem+json media type.
    """

    type: str
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None


class PaginatedResponse(BaseModel):
    """Generic paginated list wrapper."""

    items: list[Any]
    total: int
    limit: int
    offset: int
    has_more: bool

    @classmethod
    def from_list(cls, items: list, total: int, limit: int, offset: int) -> PaginatedResponse:
        return cls(
            items=items,
            total=total,
            limit=limit,
            offset=offset,
            has_more=(offset + len(items)) < total,
        )
